### ISSUE TITLE
Species-specific aspects of character creation are funny between loading different saves

### ISSUE THREAD

**Issue by tiramisuapimancer** [HearthOfHestia/Nebula#80] opened 2021-09-26 06:02 UTC
#### Description of issue
Switching between save-slots of characters of different species from each other will screw with your character's bodytype and age, but this doesn't actually carry over to the saved file- hitting "reload slot" will restore the correct bodytype and age of that character slot. This seems to happen with species that have different bodytype selections and/or age limits. 

#### Difference between expected and actual behavior
Switching slots should actually load aspects from that slot into the creator when you switch the slot. You shouldn't have to hit "reload slot" to have those load.

#### Steps to reproduce
1. Have/make a saved file, with a character who has some sort of age and some sort of body type. Easiest example is human.
2. Have/make a saved file of a character of a different species than the first one, which has a different set of body types and/or range of ages than the save from step 1. Easiest example is Adherent.
3. Switch saves. In the example of switching from the Adherent save to the human, the human's age will always be 69 (the maximum age limit for humans) even if it isn't set to that in the save file, and the human's body shape will always be feminine (the first on the list), even if it wasn't. Switching from the human save to the Adherent will set your Adherent's age to 4000 (the minimum age limit for Adherents) and their body type to Turquoise (the first on the list). 
4. Hit 'reload slot' and the values will be restored to what you actually had them set to.

#### Length of time in which bug has been known to occur

at least the last two rounds

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment] 2021-10-01 03:59
Would like to know if this persists after https://github.com/NebulaSS13/Nebula/pull/2109 is pulled in.

**Comment by MistakeNot4892** [comment] 2021-11-14 11:31
Likely related to/duplicate of #158 - changes on Neb made pronoun and bodytype reset more consistent so appears to be a different problem.

**Comment by tiramisuapimancer** [comment] 2021-11-14 11:46
that one looks to be the same issue as this, yeah

**Closed as completed** 2021-11-14 14:40 UTC
Labels: bug, duplicate, help wanted, upstream issue
